name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the file
        run: |
          cd /home/runner/work/vacuum-card/vacuum-card
          npm install
          npm run lint
          npm run build
